name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/wmCoffee.png
    - images/latte.jpg
    - images/mocha.jpg
    - images/cappuccino.jpg
    - images/americano.jpg
  fonts:
    - family: HOUTSNER_034557
      fonts:
        - asset: fonts/HOUTSNER_034557.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.otf
    - family: Poppins-Light
      fonts:
        - asset: fonts/Poppins-Light.otf
          
    
